FROM ubuntu:20.04
RUN groupadd -g 7777 webgroup && useradd -u 7777 -g webgroup -m webuser
RUN mkdir -p /home/webuser/.ssh
RUN mkdir -p /home/webuser/html
RUN chown root:root /home/webuser
RUN chmod 755 /home/webuser
RUN apt update; DEBIAN_FRONTEND=noninteractive apt install -yq openssh-server; chmod 755 /home/webuser; chown webuser:webgroup /run
COPY sftp_entrypoint.sh /entrypoint.sh
COPY sftp.conf /etc/ssh/sshd_config.d/sftp.conf
EXPOSE 22
USER root
ENTRYPOINT /entrypoint.sh
