FROM python:3.13.1
RUN cd /bin; curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"; chmod +x /bin/kubectl
RUN pip install kubernetes legacycrypt passlib mysqlclient Django cryptography requests geoip2 cloudflare urllib3==2.3.0
